plugins {
    id 'java'
}

group = 'com.Lino.battlePass'
version = 'v8.2.5'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven {
        name = "papermc"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }
    maven { url 'https://mvn.lumine.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.84-stable'
    implementation "com.zaxxer:HikariCP:7.1.0"
    implementation "com.mysql:mysql-connector-j:9.7.0"
    compileOnly 'me.clip:placeholderapi:2.12.2'
    compileOnly 'io.lumine:Mythic-Dist:5.12.0'
}

tasks.jar {
    archiveBaseName.set("BattlePass-Fork")
}

tasks.processResources {
    filesMatching("plugin.yml") {
        expand(
                version: project.version,
                name: project.name,
                group: project.group
        )
    }
}
