name: BattlePass-Fork
version: '7.5.1'
main: com.Lino.battlePass.BattlePass
api-version: '1.21'
author: Lino, golovin12
website: https://github.com/flyawaymaking/BattlePass-Fork
softdepend: [PlaceholderAPI, MythicMobs]

libraries:
  - com.zaxxer:HikariCP:5.1.0
  - com.mysql:mysql-connector-j:8.3.0

commands:
  battlepass:
    description: Open the BattlePass GUI or manage battle pass system
    usage: /battlepass [help|reload|addpremium|removepremium|addxp|removexp|addcoins|removecoins] [player] [amount]
    aliases: [bp, pass]
    permission: battlepass.use
    permission-message: You don't have permission to use this command!

permissions:
  battlepass.use:
    description: Allows use of /battlepass command
    default: true
  battlepass.admin:
    description: Access to admin commands (reload, addpremium, removepremium)
    default: op
