name: ${name}
version: ${version}
main: ${group}.BattlePass
api-version: '1.21'
authors:
  - Lino
  - golovin12
website: https://github.com/flyawaymaking
softdepend: [PlaceholderAPI, MythicMobs]

commands:
  battlepass:
    description: Open the BattlePass GUI or manage battle pass system
    usage: /battlepass [help|reload|addpremium|removepremium|addxp|removexp|addcoins|removecoins] [player] [amount]
    aliases: [bp, pass]
    permission: battlepass.use
    permission-message: You don't have permission to use this command!

permissions:
  battlepass.use:
    description: Allows use of /battlepass command
    default: true
  battlepass.admin:
    description: Access to admin commands (reload, addpremium, removepremium)
    default: op
